In [87]:
import pandas as pd
import re

In [88]:
kagglepath =  "../../dataset/kgdataset.csv"
surveypath = "../../dataset/survey_data.xlsx"
df = pd.read_csv(kagglepath)
df2 = pd.read_excel(surveypath)
df2.drop(df2.columns[0],axis=1, inplace=True)
df2.columns = df.columns
combined = pd.concat([df, df2], ignore_index=True)
combined

,Age,Sleep Hours,Feel Rested,Daily Screen Time,Use Before Sleep,Stress Level,Anxiety/Low Mood,Wellness Apps,Sleep Quality,Screen Time Affects Sleep?
0,47,4,Yes,11,Yes,10,No,No,Bad,Yes
1,48,4,No,8,No,7,Yes,Yes,Bad,Yes
2,40,7,Sometimes,10,No,4,No,Yes,Bad,Yes
3,26,10,Yes,5,Yes,1,Yes,No,Good,No
4,47,5,Yes,7,Yes,7,Yes,No,Good,Yes
...,...,...,...,...,...,...,...,...,...,...
1181,21,10,สดชื่น,8,ใช่,4,ไม่หงุดหงิด/ไม่วิตกกังวล,ใช่,ดี,ไม่แน่ใจ
1182,17,7-8,ไม่สดชื่น,>8ชม.,ใช่,8,ไม่หงุดหงิด/ไม่วิตกกังวล,ไม่ใช่,ดี,ไม่แน่ใจ
1183,17,6-8,สดชื่น,3-4,ใช่,6,ไม่หงุดหงิด/ไม่วิตกกังวล,ใช่,ไม่ดี,ใช่
1184,17,6,ไม่สดชื่น,4,ใช่,6,ไม่หงุดหงิด/ไม่วิตกกังวล,ไม่ใช่,ไม่ดี,ใช่
1185,16,8,สดชื่น,8,ใช่,1,ไม่หงุดหงิด/ไม่วิตกกังวล,ไม่ใช่,ดี,ใช่

In [89]:
dfclean = pd.DataFrame(combined)
dfclean["Feel Rested"] = dfclean["Feel Rested"].replace("ไม่สดชื่น", "No").replace("สดชื่น", "Yes")
dfclean["Use Before Sleep"] = dfclean["Use Before Sleep"].replace("ไม่ใช่", "No").replace("ใช่", "Yes")
dfclean["Anxiety/Low Mood"] = dfclean["Anxiety/Low Mood"].replace("ไม่หงุดหงิด/ไม่วิตกกังวล", "No").replace("หงุดหงิด/วิตกกังวล", "Yes")
dfclean["Wellness Apps"] = dfclean["Wellness Apps"].replace("ไม่ใช่", "No").replace("ใช่", "Yes")
dfclean["Sleep Quality"] = dfclean["Sleep Quality"].replace("ไม่ดี", "Bad").replace("ดี", "Good")
dfclean["Screen Time Affects Sleep?"] = dfclean["Screen Time Affects Sleep?"].replace("ไม่แน่ใจ", "Not Sure").replace("ใช่", "Yes").replace("ไม่ใช่", "No")

In [90]:
#check for null values and duplicates
print(dfclean.isnull().sum())
duplicates = dfclean[dfclean.duplicated()]
print("Duplicate Rows:")
print(duplicates)
dfclean = dfclean.drop_duplicates()
print("DataFrame after removing duplicates:")
print(dfclean)

Age                           0
Sleep Hours                   0
Feel Rested                   0
Daily Screen Time             0
Use Before Sleep              0
Stress Level                  0
Anxiety/Low Mood              0
Wellness Apps                 0
Sleep Quality                 0
Screen Time Affects Sleep?    0
dtype: int64
Duplicate Rows:
    Age Sleep Hours Feel Rested Daily Screen Time Use Before Sleep  \
181  15          10          No                 2               No
358  53           4   Sometimes                 9              Yes
452  17           8          No                 4              Yes
739  39           8   Sometimes                 2               No
955  51          10   Sometimes                 5               No

     Stress Level Anxiety/Low Mood Wellness Apps Sleep Quality  \
181             5               No            No          Good
358             8               No            No           Bad
452             3               No            No          Good
739             2              Yes           Yes          Good
955             6               No           Yes          Good

    Screen Time Affects Sleep?
181                         No
358                        Yes
452                         No
739                         No
955                         No
DataFrame after removing duplicates:
     Age Sleep Hours Feel Rested Daily Screen Time Use Before Sleep  \
0     47           4         Yes                11              Yes
1     48           4          No                 8               No
2     40           7   Sometimes                10               No
3     26          10         Yes                 5              Yes
4     47           5         Yes                 7              Yes
...   ..         ...         ...               ...              ...
1181  21          10         Yes                 8              Yes
1182  17         7-8          No             >8ชม.              Yes
1183  17         6-8         Yes               3-4              Yes
1184  17           6          No                 4              Yes
1185  16           8         Yes                 8              Yes

      Stress Level Anxiety/Low Mood Wellness Apps Sleep Quality  \
0               10               No            No           Bad
1                7              Yes           Yes           Bad
2                4               No           Yes           Bad
3                1              Yes            No          Good
4                7              Yes            No          Good
...            ...              ...           ...           ...
1181             4               No           Yes          Good
1182             8               No            No          Good
1183             6               No           Yes           Bad
1184             6               No            No           Bad
1185             1               No            No          Good

     Screen Time Affects Sleep?
0                           Yes
1                           Yes
2                           Yes
3                            No
4                           Yes
...                         ...
1181                   Not Sure
1182                   Not Sure
1183                        Yes
1184                        Yes
1185                        Yes

[1181 rows x 10 columns]

In [91]:
#clean age
def extract_number(value):
    if "-" in str(value):
        value = re.sub(r'[^\d\-\.]', '', value)
        values = str(value).split("-")
        return f"{values[0]}-{values[1]}"
    elif isinstance(value, str):
        result = pd.Series(value).str.extract('(\d+)') 
        return result[0].iloc[0] if not result.empty else None

    else:
        return str(value)      
dfclean["Age"] = dfclean["Age"].apply(extract_number)

#clean sleep hours by mean
def clean_range_with_mean(value):
    if isinstance(value, str):
        if '-' in value:
            try:
                low, high = map(float, value .split('-'))
                return (low + high) / 2
            except ValueError:
                return value
        else:
            try:
                return float(value)
            except ValueError:
                return value
    else:
        return value
dfclean["Sleep Hours"] = dfclean["Sleep Hours"].apply(extract_number)
dfclean["Sleep Hours"] = dfclean["Sleep Hours"].apply(clean_range_with_mean)

#Clean Daily Screen Time
dfclean["Daily Screen Time"] = dfclean["Daily Screen Time"].apply(extract_number)
dfclean["Daily Screen Time"] = dfclean["Daily Screen Time"].apply(clean_range_with_mean)
print(dfclean["Sleep Hours"].isnull().sum())
print(dfclean["Age"].isnull().sum())
print(dfclean["Daily Screen Time"].isnull().sum())

0
0
0

In [92]:
dfclean.tail(60)

,Age,Sleep Hours,Feel Rested,Daily Screen Time,Use Before Sleep,Stress Level,Anxiety/Low Mood,Wellness Apps,Sleep Quality,Screen Time Affects Sleep?
1126,20,8.0,No,10.0,Yes,1,No,Yes,Bad,Yes
1127,22,5.0,No,2.0,Yes,4,No,No,Bad,Yes
1128,19,6.0,Yes,10.0,Yes,7,Yes,No,Good,Yes
1129,20,8.0,Yes,4.0,Yes,7,No,No,Good,Yes
1130,23,9.0,No,10.0,Yes,7,Yes,Yes,Good,Not Sure
1131,100,1.0,No,20.0,Yes,10,Yes,Yes,Bad,Yes
1132,20,6.0,Yes,11.0,Yes,7,No,Yes,Bad,Yes
1133,19,5.0,No,10.0,Yes,7,Yes,No,Good,Yes
1134,21,10.0,No,8.0,Yes,7,Yes,No,Bad,Yes
1135,21,7.0,Yes,6.0,Yes,3,No,No,Good,Yes
1136,23,6.5,Yes,12.0,Yes,5,Yes,No,Good,Not Sure
1137,20,6.0,No,14.0,Yes,6,No,Yes,Bad,Yes
1138,22,5.0,Yes,3.5,Yes,5,No,No,Good,Not Sure
1139,20,5.0,No,7.0,Yes,4,No,No,Bad,Not Sure
1140,21,6.0,Yes,7.0,Yes,5,No,Yes,Good,Not Sure
1141,21,6.0,No,15.0,Yes,5,Yes,No,Bad,Yes
1142,22,6.0,No,5.0,Yes,5,No,Yes,Bad,Yes
1143,18,6.0,Yes,7.5,Yes,5,No,No,Good,No
1144,18,12.0,Yes,12.0,Yes,3,No,No,Good,No
1145,17,5.5,No,14.0,Yes,7,Yes,Yes,Good,Yes
1146,17,10.0,Yes,4.0,Yes,2,No,No,Good,Yes
1147,17,9.0,Yes,6.0,Yes,2,No,Yes,Good,No
1148,18,8.0,Yes,2.0,Yes,7,No,Yes,Good,Yes
1149,17,7.5,Yes,5.0,Yes,10,No,No,Good,Not Sure
1150,17,7.0,Yes,10.0,Yes,7,No,No,Good,Yes
1151,18,7.5,No,17.0,Yes,7,No,No,Bad,Yes
1152,17,7.5,No,7.0,Yes,3,No,Yes,Good,Not Sure
1153,17,8.0,Yes,8.0,Yes,5,No,Yes,Good,No
1154,17,10.0,Yes,13.0,Yes,6,No,No,Good,No
1155,19,6.0,No,12.0,Yes,7,No,No,Bad,Yes
1156,21,5.0,No,18.0,Yes,5,No,No,Good,Not Sure
1157,16,6.0,Yes,10.0,Yes,10,No,No,Bad,Yes
1158,36,4.5,No,15.0,Yes,8,Yes,No,Bad,Yes
1159,29,4.0,No,5.0,Yes,3,No,No,Good,No
1160,17,5.0,No,1.5,Yes,9,No,No,Good,Not Sure
1161,16,7.0,Yes,7.0,Yes,8,No,Yes,Bad,Yes
1162,18,8.0,No,13.0,Yes,5,No,No,Bad,Not Sure
1163,17,9.0,No,11.3,Yes,1,No,Yes,Good,No
1164,17,2.5,No,20.0,Yes,4,Yes,No,Bad,Yes
1165,18,8.0,Yes,5.0,Yes,4,Yes,No,Good,Not Sure
1166,19,6.5,No,10.0,Yes,7,No,No,Bad,Yes
1167,18,7.0,No,10.0,Yes,5,No,No,Bad,Yes
1168,16,10.0,No,9.5,Yes,6,Yes,Yes,Bad,Yes
1169,18,6.0,Yes,6.0,Yes,5,No,No,Bad,Yes
1170,21,8.0,Yes,5.0,Yes,4,No,Yes,Good,Not Sure
1171,20,8.0,No,7.0,Yes,7,No,Yes,Bad,Yes
1172,21,6.5,No,10.0,Yes,8,Yes,Yes,Bad,Yes
1173,17,9.0,Yes,10.0,Yes,4,No,No,Good,Yes
1174,21,7.0,No,10.0,Yes,5,No,Yes,Good,No
1175,31,5.0,No,6.0,Yes,3,No,No,Bad,Not Sure
1176,18,9.0,No,10.0,Yes,7,Yes,No,Bad,Not Sure
1177,31,5.0,No,18.0,Yes,5,No,Yes,Good,No
1178,53,7.0,Yes,2.0,Yes,8,No,No,Good,Not Sure
1179,18,8.0,Yes,7.0,Yes,4,No,No,Good,Yes
1180,18,8.5,No,12.0,Yes,5,Yes,No,Good,Not Sure
1181,21,10.0,Yes,8.0,Yes,4,No,Yes,Good,Not Sure
1182,17,7.5,No,8.0,Yes,8,No,No,Good,Not Sure
1183,17,7.0,Yes,3.5,Yes,6,No,Yes,Bad,Yes
1184,17,6.0,No,4.0,Yes,6,No,No,Bad,Yes
1185,16,8.0,Yes,8.0,Yes,1,No,No,Good,Yes